# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
  	setup_circle_ci
  end

  desc "Build and run tests"
  lane :test do
    scan
  end

  desc "Ad-hoc build"
  lane :adhoc do
    match(type: "adhoc")
    gym(export_method: "ad-hoc")
    firim(firim_api_token:"5f6124c0e1b48f9517930abd9386e080", app_changelog: "#{changelog.to_s}")
  end
  # desc "Push a new release build to the App Store"
  # lane :release do
  #   build_app(scheme: "TableViewRefreshControlDemo")
  #   upload_to_app_store(skip_metadata: true, skip_screenshots: true)

  #   firim(firim_api_token:"5f6124c0e1b48f9517930abd9386e080", app_changelog: "#{changelog.to_s}")
  # end
end
